// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file api/calculator.proto (package calculator, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/calculator.proto.
 */
export const file_api_calculator: GenFile = /*@__PURE__*/
  fileDesc("ChRhcGkvY2FsY3VsYXRvci5wcm90bxIKY2FsY3VsYXRvciI7ChBDYWxjdWxhdGVSZXF1ZXN0EgkKAWEYASABKAESCQoBYhgCIAEoARIRCglvcGVyYXRpb24YAyABKAkiMgoRQ2FsY3VsYXRlUmVzcG9uc2USDgoGcmVzdWx0GAEgASgBEg0KBWVycm9yGAIgASgJMl8KEUNhbGN1bGF0b3JTZXJ2aWNlEkoKCUNhbGN1bGF0ZRIcLmNhbGN1bGF0b3IuQ2FsY3VsYXRlUmVxdWVzdBodLmNhbGN1bGF0b3IuQ2FsY3VsYXRlUmVzcG9uc2UiAEIQWg5jYWxjdWxhdG9yL2FwaWIGcHJvdG8z");

/**
 * @generated from message calculator.CalculateRequest
 */
export type CalculateRequest = Message<"calculator.CalculateRequest"> & {
  /**
   * @generated from field: double a = 1;
   */
  a: number;

  /**
   * @generated from field: double b = 2;
   */
  b: number;

  /**
   * "add", "subtract", "multiply", "divide"
   *
   * @generated from field: string operation = 3;
   */
  operation: string;
};

/**
 * Describes the message calculator.CalculateRequest.
 * Use `create(CalculateRequestSchema)` to create a new message.
 */
export const CalculateRequestSchema: GenMessage<CalculateRequest> = /*@__PURE__*/
  messageDesc(file_api_calculator, 0);

/**
 * @generated from message calculator.CalculateResponse
 */
export type CalculateResponse = Message<"calculator.CalculateResponse"> & {
  /**
   * @generated from field: double result = 1;
   */
  result: number;

  /**
   * @generated from field: string error = 2;
   */
  error: string;
};

/**
 * Describes the message calculator.CalculateResponse.
 * Use `create(CalculateResponseSchema)` to create a new message.
 */
export const CalculateResponseSchema: GenMessage<CalculateResponse> = /*@__PURE__*/
  messageDesc(file_api_calculator, 1);

/**
 * @generated from service calculator.CalculatorService
 */
export const CalculatorService: GenService<{
  /**
   * @generated from rpc calculator.CalculatorService.Calculate
   */
  calculate: {
    methodKind: "unary";
    input: typeof CalculateRequestSchema;
    output: typeof CalculateResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_calculator, 0);

